# Generated by Django 5.2.4 on 2025-07-22 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('basic', 'Basic Nursing Skills'), ('assessment', 'Assessment Skills'), ('medication', 'Medication Administration'), ('procedures', 'Clinical Procedures'), ('emergency', 'Emergency Skills'), ('communication', 'Communication Skills')], max_length=50)),
                ('description', models.TextField()),
                ('steps', models.TextField(help_text='Step-by-step procedure')),
                ('safety_considerations', models.TextField()),
                ('equipment_needed', models.TextField()),
                ('competency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NCLEXQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('select_all', 'Select All That Apply'), ('fill_blank', 'Fill in the Blank'), ('drag_drop', 'Drag and Drop')], default='multiple_choice', max_length=20)),
                ('options', models.JSONField(default=list)),
                ('correct_answers', models.JSONField(default=list)),
                ('rationale', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TulipVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('bloom_time', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('care_instructions', models.TextField()),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='flashcards/')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.flashcarddeck')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('content', 'Content'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('stressed', 'Stressed')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('fundamentals', 'Fundamentals of Nursing'), ('anatomy_physiology', 'Anatomy & Physiology'), ('pharmacology', 'Pharmacology'), ('pathophysiology', 'Pathophysiology'), ('medical_surgical', 'Medical-Surgical Nursing'), ('pediatric', 'Pediatric Nursing'), ('maternity', "Maternity & Women's Health"), ('mental_health', 'Mental Health Nursing'), ('community_health', 'Community Health Nursing'), ('critical_care', 'Critical Care Nursing'), ('nursing_ethics', 'Nursing Ethics & Law'), ('research', 'Nursing Research')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlanSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('target_hours', models.IntegerField(default=10)),
                ('completed_hours', models.IntegerField(default=0)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studyplan')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.note')),
            ],
        ),
        migrations.AddField(
            model_name='studyplan',
            name='subjects',
            field=models.ManyToManyField(through='core.StudyPlanSubject', to='core.note'),
        ),
    ]
